[package]
name = "ping"
version = "0.1.0"
authors = ["13abel <therichardwei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
nix = "0.17.0"
pnet = "0.25.0"
